export const siteConfig = {
  name: "Digital Future",
  url: "https://www.bestdigitalmarket.in",
  domainName: "Best Digital Market",
  title: "Best Web Design Company, SEO & Digital Marketing Agency in Noida",
  description:
    "Best Digital Market by Digital Future provides SEO-friendly website design, web development, software, CRM, SEO, Google Ads and lead generation services for Noida, Greater Noida, Delhi NCR, Mumbai, Pune, Chandigarh and India.",
  callNumber: "9992196879",
  whatsappNumber: "9350031246",
  email: "amit.tech1970@gmail.com",
  address: "Sector MU-1, Greater Noida 201310, India",
  mapUrl: "https://www.google.com/maps/search/?api=1&query=Sector%20MU-1%2C%20Greater%20Noida%20201310",
  areas: ["All India", "Noida", "Greater Noida", "Delhi NCR", "Mumbai", "Pune", "Chandigarh", "Faridabad", "Gurugram", "Ghaziabad"],
  social: {
    linkedin: "https://www.linkedin.com/in/amittech",
    github: "https://github.com/amittech",
    instagram: "#",
    facebook: "#",
  },
  keywords: [
    "best web design company in Noida",
    "best web design company in Greater Noida",
    "SEO friendly website development in Noida",
    "website development company in Greater Noida",
    "web design and SEO company in Noida",
    "web design and SEO company in Greater Noida",
    "affordable website design company in Noida",
    "business website developer in Greater Noida",
    "Next.js website development company India",
    "custom website development services India",
    "digital marketing agency in Noida",
    "digital marketing company in Greater Noida",
    "SEO company in Noida",
    "local SEO services in Greater Noida",
    "Google Business Profile optimization Noida",
    "technical SEO audit services India",
    "AEO GEO SEO services India",
    "LLM SEO services India",
    "Google Ads agency in Noida",
    "Meta Ads lead generation agency India",
    "lead generation agency Delhi NCR",
    "performance marketing agency India",
    "digital marketing agency in Mumbai",
    "SEO agency in Mumbai",
    "website development agency in Mumbai",
    "digital marketing agency in Pune",
    "website development company in Pune",
    "SEO services in Pune",
    "digital marketing agency in Chandigarh",
    "SEO company in Chandigarh",
    "website design company in Chandigarh",
    "software development company in Noida",
    "custom software development company India",
    "CRM development services India",
    "mobile app development company India",
    "business automation services India",
  ],
};

export const whatsappLink = `https://wa.me/91${siteConfig.whatsappNumber}?text=${encodeURIComponent(
  "Hi, I want a free digital marketing consultation."
)}`;

export const callLink = `tel:+91${siteConfig.callNumber}`;
